export const CONVERT_NUMBER_REQUEST = "CONVERT_NUMBER_REQUEST";
export const CONVERT_NUMBER_SUCCESS = "CONVERT_NUMBER_SUCCESS";
export const CONVERT_NUMBER_ERROR = "CONVERT_NUMBER_ERROR";

export const REFRESH_STORE = "REFRESH_STORE";

export const SET_CONVERTED_NUMBER = "SET_CONVERTED_NUMBER";
